services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    healthcheck:
      test: [ CMD, mongosh, --eval, db.runCommand('ping').ok, --quiet ]
      interval: 2s
      timeout: 2s
      retries: 10

networks:
  default:
    name: network
